# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_ca <- function(dfm, residual_floor, threads = -1L) {
    .Call(`_quanteda_textmodels_cpp_ca`, dfm, residual_floor, threads)
}

cpp_svmlin <- function(X, y, l, algorithm, lambda, lambda_u, max_switch, pos_frac, Cp, Cn, costs, verbose) {
    .Call(`_quanteda_textmodels_cpp_svmlin`, X, y, l, algorithm, lambda, lambda_u, max_switch, pos_frac, Cp, Cn, costs, verbose)
}

qatd_cpp_tbb_enabled <- function() {
    .Call(`_quanteda_textmodels_qatd_cpp_tbb_enabled`)
}

cpp_wordfish_dense <- function(wfm, dir, priors, tol, disp, dispfloor, abs_err) {
    .Call(`_quanteda_textmodels_cpp_wordfish_dense`, wfm, dir, priors, tol, disp, dispfloor, abs_err)
}

